### ISSUE TITLE
This script not working for me 

### ISSUE THREAD

**Issue by Ranveer20** [abulimov/utils#1]
Hello,

I am gating below error when i run script, its working fine to show the existing maintenance name 
 ./zabbix_maintenance.py --user=Admin --password=zabbix --server=http://172.27.11.21/zabbix/ create hi --groups cloud --period=5 --no-data --force

(u'Error -32602: Invalid params., Incorrect method "maintenance.exists". while sending {"params": {"name": "hi"}, "jsonrpc": "2.0", "method": "maintenance.exists", "auth": "fcb1dd59984351ea59e8f172238380bc", "id": 1}', -32602)

Please help me to understand

**Comment by zhelanov** [comment]
https://github.com/abulimov/utils/pull/2

**Comment by abulimov** [comment]
Resolved by #2
